seldonian.models.zhat\_funcs.vector\_Error
==========================================

.. currentmodule:: seldonian.models.zhat_funcs

.. autofunction:: vector_Error